proto model 초안 & user_service.proto 추가
DDD-6/appcha-protobuf pull request #2
Opened 2021-10-26 14:22 UTC by HongJow

2021-10-28 02:09 UTC, laco-dev requested changes
유저만 먼저해서 따로 올려주셔도 되었는데,
피드랑 보드가 같이 섞여서 컨텍스트가 많아 진 것 같네요

2021-10-28 02:09 UTC, laco-dev commented on protobuf/model/board.proto
> +    }
분류할 정도로 의미있는 Board가 쌓일 것 같지 않다고판단해서 분류를 제거했는데요.
https://www.figma.com/file/Q23Y0ZDAlRHoyqJset1nrq?node-id=213:230#118804755

혹시 Category를 분류하는게 더 좋다고 생각되시면 톡방에서 추가로 얘기 던져주세요!

2021-10-28 02:09 UTC, laco-dev commented on protobuf/model/board.proto
> +    int64 created_at = 6;
본문도 추가 해 주세요 `body`

2021-10-28 02:09 UTC, laco-dev commented on protobuf/model/common.proto
> +}
`google.protobuf.StringValue` 대신에 직접 만드신 이유가 있나요?
https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#stringvalue

2021-10-28 02:09 UTC, laco-dev commented on protobuf/model/feed.proto
> +    }
피드도 카테고리가 현재 없는 단계이긴 해서 나중에 필요하면 그 때 추가해도 될 것 같습니다.

2021-10-28 02:09 UTC, laco-dev commented on protobuf/model/feed.proto
> +    }
enum은 protobuf 스타일 가이드에 맞춘다면 `CATEGORY_UNSPEICIFED`가 되야 할 것 같습니다.
https://developers.google.com/protocol-buffers/docs/style?hl=ko#enums

2021-10-28 02:09 UTC, laco-dev commented on protobuf/model/feed.proto
> +    repeated App apps = 6;
피드에 대한 메인 썸네일 이미지 필요합니다.

2021-10-28 02:09 UTC, laco-dev commented on protobuf/model/feed.proto
> +    int32 upvote_count = 10;
좋아요 개수는 디자인상에서는 현재 빠져서 proto에서는 빼도 될 것 같네요

2021-10-28 02:09 UTC, laco-dev commented on protobuf/model/feed.proto
> +    }
Body의 종류는 Type + Data 보다는 oneof로 각각의 메세지들을 따로 만들어 주세요

2021-10-28 02:09 UTC, laco-dev commented on protobuf/model/feed.proto
> +}
각 타입이 어떤거랑 매칭되는지 잘 이해가 되지 않습니다.
따로 공유 부탁드립니다

2021-10-28 02:09 UTC, laco-dev commented on protobuf/service/user_service.proto
> +    string access_token = 1; // kakao access token
바로 `kakao_access_token`으로 명시해주시면 변수로만 의미를 담을 수 있을 것 같습니다.

2021-10-28 02:09 UTC, laco-dev commented on protobuf/service/user_service.proto
> +    string token = 1; // appcha server token
이거를 그냥 `access_token`으로 해 주시면 됩니다

2021-10-28 02:09 UTC, laco-dev commented on protobuf/service/user_service.proto
> +}
https://developers.google.com/protocol-buffers/docs/style?hl=ko#standard_file_formatting
indent는 2로 맞춰주세요

2021-10-28 09:11 UTC, peterchoee approved these changes
gRPC 스펙이 처음이라 이견은 없고 클라이어트에서 진행하면서 궁금한 부분은 문의드릴게요!
영직님이 리뷰주신 kakao_access_token, access_token 정도만 구분되면 좋을 것 같습니다 👍

2021-10-30 03:53 UTC, laco-dev requested changes

2021-10-30 03:53 UTC, laco-dev commented on protobuf/model/app.proto
> +    App app = 1;
AppDetail에서 App을 역참조하는것은 안된다고 생각합니다.
필요한 정보라면 중복해서 한번 더 추가해야 할 것 같아요.

2021-10-30 03:53 UTC, laco-dev commented on protobuf/model/feed.proto
> +    User author = 3;
Feed에서 필요한건 유저의 아이디나 닉네임 정도입니다.
User를 그대로 만드는 것은 불필요해 보여요

2021-10-30 05:07 UTC, HongJow commented on protobuf/model/common.proto
> +}
아 여기선 import하는 게 좋겠네요. 수정하겠습니다~

2021-10-30 05:17 UTC, HongJow commented on protobuf/model/feed.proto
> +    }
아 그러면 Oneof로 text, head, image_url 등을 넣는게 좋을까요?

2021-10-30 05:17 UTC, HongJow commented on protobuf/model/feed.proto
> +}
요건 영직님이 위에서 말씀하신 대로 하면 타입은 빼도 괜찮을 것 같습니다 :)

2021-10-30 12:53 UTC, laco-dev approved these changes
서버 구현도 우선 하셔야되니 승인하겠습니다.
드린 커멘트는 다음 작업에서 같이 반영 부탁드립니다

2021-10-30 12:53 UTC, laco-dev commented on protobuf/model/app.proto
> +}
AppDetail은 지금 스펙상으로는 안쓸 것 같습니다.
마켓으로 이동하는정도에서 끝날 듯 해요

2021-10-30 12:53 UTC, laco-dev commented on protobuf/model/feed.proto
> +}
여기는 단톡방에서 얘기한 타입 기준 정리되면 반영해주세요
현재는 Text, Image, App 이렇게 잡고있습니다

2021-10-30 12:58 UTC, merged